### ISSUE TITLE
作者您好，为什么我在运行train的时候，出现以下问题，我该怎么解决呢？

### ISSUE THREAD

**Issue by Xback-yx** [yingernnn/transclawunet#1]

**Comment by Xback-yx** [comment]
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from trainer import trainer_synapse
  File "/data2/wangq/TransClawUNet/trainer.py", line 17, in <module>
    from love import lovasz_softmax
  File "/home/wangq/anaconda3/lib/python3.8/site-packages/love/__init__.py", line 8, in <module>
    from .love import main, __version__
  File "/home/wangq/anaconda3/lib/python3.8/site-packages/love/love.py", line 34, in <module>
    from .flit import python_requires
  File "/home/wangq/anaconda3/lib/python3.8/site-packages/love/flit.py", line 7, in <module>
    from flit.inifile import _validate_config, _read_pkg_ini
ModuleNotFoundError: No module named 'flit.inifile'

**Comment by Leslic18** [comment]
> Traceback (most recent call last): File "train.py", line 10, in from trainer import trainer_synapse File "/data2/wangq/TransClawUNet/trainer.py", line 17, in from love import lovasz_softmax File "/home/wangq/anaconda3/lib/python3.8/site-packages/love/**init**.py", line 8, in from .love import main, **version** File "/home/wangq/anaconda3/lib/python3.8/site-packages/love/love.py", line 34, in from .flit import python_requires File "/home/wangq/anaconda3/lib/python3.8/site-packages/love/flit.py", line 7, in from flit.inifile import _validate_config, _read_pkg_ini ModuleNotFoundError: No module named 'flit.inifile'

我也遇到了这个问题 请问你解决了吗 可以交流一下
